apiVersion: v1
kind: Service
metadata:
  name: phoenix-service
  namespace: phoenix-app
  labels:
    app: phoenix-reviews
spec:
  type: LoadBalancer
  selector:
    app: phoenix-reviews
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
